In [ ]:
# 📦 Step 1: Import Libraries
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix
from scipy.stats import uniform
import numpy as np

# 🧪 Step 2: Create Multi-Class Classification Data
X, y = make_classification(n_samples=1000, 
                           n_features=10, 
                           n_informative=3, 
                           n_classes=3, 
                           random_state=42)

# ✂️ Step 3: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 🧠 Step 4: Initialize and Train Logistic Regression Model (Base Version)
model = LogisticRegression(multi_class='ovr')
model.fit(X_train, y_train)

# 🔮 Step 5: Make Predictions
y_pred = model.predict(X_test)

# 📊 Step 6: Evaluate the Base Model
print("Base Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 🔍 Step 7: GridSearchCV (Exhaustive Hyperparameter Tuning)
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['lbfgs', 'saga'],
    'multi_class': ['ovr', 'multinomial'],
    'max_iter': [100, 200, 500]
}

grid_model = LogisticRegression()
grid_search = GridSearchCV(estimator=grid_model, param_grid=param_grid, cv=5, verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)

# 🔍 Step 8: Evaluate Best GridSearchCV Model
best_grid_model = grid_search.best_estimator_
y_pred_grid = best_grid_model.predict(X_test)
print("\nGridSearchCV Best Model")
print("Best Parameters:", grid_search.best_params_)
print("Accuracy:", accuracy_score(y_test, y_pred_grid))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_grid))

# 🎲 Step 9: RandomizedSearchCV (Faster Tuning)
param_dist = {
    'C': uniform(loc=0.01, scale=10),
    'solver': ['lbfgs', 'saga'],
    'multi_class': ['ovr', 'multinomial'],
    'max_iter': [100, 200, 500]
}

random_model = LogisticRegression()
random_search = RandomizedSearchCV(estimator=random_model, param_distributions=param_dist,
                                   n_iter=10, cv=5, verbose=1, n_jobs=-1, random_state=42)
random_search.fit(X_train, y_train)

# 🎲 Step 10: Evaluate Best RandomizedSearchCV Model
best_random_model = random_search.best_estimator_
y_pred_random = best_random_model.predict(X_test)
print("\nRandomizedSearchCV Best Model")
print("Best Parameters:", random_search.best_params_)
print("Accuracy:", accuracy_score(y_test, y_pred_random))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_random))

# Base Logistic Regression
# Accuracy: 0.65
# Confusion Matrix:
#  [[49 12  5]
#  [25 27 17]
#  [ 2  9 54]]
# Fitting 5 folds for each of 48 candidates, totalling 240 fits

# GridSearchCV Best Model
# Best Parameters: {'C': 0.1, 'max_iter': 100, 'multi_class': 'multinomial', 'solver': 'lbfgs'}
# Accuracy: 0.695
# Confusion Matrix:
#  [[47 15  4]
#  [17 38 14]
#  [ 2  9 54]]
# Fitting 5 folds for each of 10 candidates, totalling 50 fits

# RandomizedSearchCV Best Model
# Best Parameters: {'C': np.float64(3.347086111390218), 'max_iter': 500, 'multi_class': 'multinomial', 'solver': 'lbfgs'}
# Accuracy: 0.695
# Confusion Matrix:
#  [[47 15  4]
#  [17 38 14]
#  [ 2  9 54]]



c:\Users\sahus\OneDrive\Desktop\Complete Data Science\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


Base Logistic Regression
Accuracy: 0.65
Confusion Matrix:
 [[49 12  5]
 [25 27 17]
 [ 2  9 54]]
Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV Best Model
Best Parameters: {'C': 0.1, 'max_iter': 100, 'multi_class': 'multinomial', 'solver': 'lbfgs'}
Accuracy: 0.695
Confusion Matrix:
 [[47 15  4]
 [17 38 14]
 [ 2  9 54]]
Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV Best Model
Best Parameters: {'C': np.float64(3.347086111390218), 'max_iter': 500, 'multi_class': 'multinomial', 'solver': 'lbfgs'}
Accuracy: 0.695
Confusion Matrix:
 [[47 15  4]
 [17 38 14]
 [ 2  9 54]]


c:\Users\sahus\OneDrive\Desktop\Complete Data Science\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\sahus\OneDrive\Desktop\Complete Data Science\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
