✅ Introduction to NumPy
•	NumPy is a very important Python library used for scientific computing.
•	It is mainly used for arrays, matrices, and fast mathematical operations.
•	NumPy is also heavily used in machine learning and deep learning.


In [8]:
#Creating array using numpy
import numpy as np
#Creating a 1D array
arr1 = np.array([1,2,3])
print(arr1) #[1 2 3]
print(type(arr1)) #<class 'numpy.ndarray'>
print(arr1.shape) #(3,) #1D array with 3 elements

#Converting 1D array to 2D array
arr2 = arr1.reshape(1,3)
print(arr2) #[[1 2 3]] # 2D array with 1 row and 3 columns

# 2D Array example:
arr3 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5,6]])
arr3.shape  # (2, 5)



[1 2 3]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]]


(2, 5)

In [ ]:
# 🧮 Array Creation Functions

import numpy as np

# 1. np.arange
# syntax: np.arange(start, stop, step)
np.arange(0, 10, 2)  
# Output: array([0, 2, 4, 6, 8])

# 2. Create matrix of ones
# syntax: np.ones((rows, columns))  
np.ones((3, 3))  
# Output: 
# array([[1., 1., 1.],
#        [1., 1., 1.],
#        [1., 1., 1.]])

# 3. np.eye(n): Creates an identity matrix (1s on the diagonal)
np.eye(3)
# Output:
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])




array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 📊 Array Attributes
# For any array arr, you can use:
# •	arr.shape: Shape of the array
# •	arr.ndim: Number of dimensions
# •	arr.size: Number of elements
# •	arr.dtype: Data type (like int32, float64)
# •	arr.itemsize: Size in bytes of one element
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr) # Output: [[1 2 3] [4 5 6]]
print("Shape:", arr.shape)  # Output: (2, 3) 
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
import numpy as np

# 🧮 Vectorized Operations
r1 = np.array([1, 2, 3, 4, 5])
r2 = np.array([10, 20, 30, 40, 50])

print("r1 + r2 =", r1 + r2)   # Addition 
print("r1 - r2 =", r1 - r2)   # Subtraction
print("r1 * r2 =", r1 * r2)   # Multiplication
print("r2 / r1 =", r2 / r1)   # Division

# r1 + r2 = [11 22 33 44 55]
# r1 - r2 = [ -9 -18 -27 -36 -45]
# r1 * r2 = [ 10  40  90 160 250]
# r2 / r1 = [10. 10. 10. 10. 10.]


r1 + r2 = [11 22 33 44 55]
r1 - r2 = [ -9 -18 -27 -36 -45]
r1 * r2 = [ 10  40  90 160 250]
r2 / r1 = [10. 10. 10. 10. 10.]


In [ ]:
# 🔢 Universal Functions (ufuncs)
# These apply to each element:
# np.sqrt(arr)      # Square root
# np.exp(arr)       # Exponential
# np.sin(arr)       # Sine
# np.log(arr)       # Natural log

import numpy as np

# 🔢 Universal Functions (ufuncs)
arr = np.array([1, 4, 9, 16, 25])

print("np.sqrt(arr) =", np.sqrt(arr))   # Square root # Output: [1. 2. 3. 4. 5.]
print("np.exp(arr) =", np.exp(arr))     # Exponential # Output: [2.71828183e+00 5.45981500e+01 8.10308393e+03 2.17848130e+07 7.20048993e+10]
print("np.sin(arr) =", np.sin(arr))     # Sine        # Output: [0.84147098 -0.7568025  0.41211849 -0.28790332 -0.13235175]
print("np.log(arr) =", np.log(arr))     # Natural log # Output: [0.         1.38629436 2.19722458 2.77258872 3.21887582]



np.sqrt(arr) = [1. 2. 3. 4. 5.]
np.exp(arr) = [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
np.sin(arr) = [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
np.log(arr) = [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [27]:
# 🔍 Indexing and Slicing
# Create a 2D array:
import numpy as np

# 🔍 Indexing and Slicing

# Create a 2D array:
arr = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
])

# Access specific element:
print("arr[0][0] =", arr[0][0])  # Output: 1

# Slice rows and columns:
print("arr[1:, 2:] =\n", arr[1:, 2:])  # Rows from index 1, columns from index 2
print("arr[1:, :2] =\n", arr[1:, :2])  # Rows from 1, first 2 columns
print("arr[:, 1:3] =\n", arr[:, 1:3])  # All rows, columns 1 and 2



arr[0][0] = 1
arr[1:, 2:] =
 [[ 7  8]
 [11 12]]
arr[1:, :2] =
 [[ 5  6]
 [ 9 10]]
arr[:, 1:3] =
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [28]:
import numpy as np

# ✏️ Modifying Arrays

# Create a 2D array
arr = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

print("Original array:\n", arr)

# Change specific element
arr[0][0] = 100
print("\nAfter arr[0][0] = 100:\n", arr)

# Change part of array
arr[1:] = 100  # Set all values from row 1 onwards to 100
print("\nAfter arr[1:] = 100:\n", arr)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After arr[0][0] = 100:
 [[100   2   3]
 [  4   5   6]
 [  7   8   9]]

After arr[1:] = 100:
 [[100   2   3]
 [100 100 100]
 [100 100 100]]


In [29]:
import numpy as np

# 📈 Statistical Operations
data = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(data))       # Mean
print("Median:", np.median(data))   # Median
print("Standard Deviation:", np.std(data))  # Standard deviation
print("Variance:", np.var(data))    # Variance


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [30]:
import numpy as np

# ⚖️ Normalization Example
data = np.array([1, 2, 3, 4, 5])

# Calculate mean and standard deviation
mean = np.mean(data)
std = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std

# Output results
print("Original data:", data)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Normalized data:", normalized_data)



Original data: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
import numpy as np

# ✅ Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Condition check
print("data > 5:", data > 5)
# Output: [False False False False False  True  True  True  True  True]

# Get values greater than 5
print("data[data > 5]:", data[data > 5])
# Output: [ 6  7  8  9 10]

# Combine multiple conditions
print("data[(data >= 5) & (data <= 8)]:", data[(data >= 5) & (data <= 8)])
# Output: [5 6 7 8]


data > 5: [False False False False False  True  True  True  True  True]
data[data > 5]: [ 6  7  8  9 10]
data[(data >= 5) & (data <= 8)]: [5 6 7 8]
